name: 'Close stale issues and PRs New'
on:
  workflow_dispatch:
  schedule:
    - cron: '55 16 * * *'


permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This is an automated message. Per our repo policy, stale issues get closed if there has been no activity in the past 28 days. The issue will be automatically closed in 14 days. If you wish to keep this issue open, please add a new comment.'
          days-before-issue-stale: 0
          days-before-pr-stale: -1
          days-before-close: 14
          operations-per-run: 2
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This is an automated message. Per our repo policy, stale issues get closed if there has been no activity in the past 60 days. The issue will be automatically closed in 14 days. If you wish to keep this issue open, please add a new comment."
          close-issue-label: 'info:new-port-unresolved'
          days-before-issue-stale: 0
          days-before-pr-stale: -1
          days-before-close: 14
          operations-per-run: 2